version: 2.1
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/node
  node: circleci/node@1.1.4
jobs:
  build-without-orb:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - run: 
          command: cd blankreact
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys: 
            - node-deps-v1-without-orbs-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          
          command: npm install # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: node-deps-v1-without-orbs-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "~/project/node_modules"

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test # replace with `yarn test` if using yarn

      - store_artifacts:
          path: test-results
      
      - store_test_results:
          path: test-results
  build-with-orb:
    executor:
      name: node/default
      tag: "10"
    steps:
      - checkout # special step to check out source code to working directory
      - run: 
          command: cd blankreact
      - node/with-cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          cache-key: package-lock.json
          cache-version: v1-with-orbs
          use-strict-cache: true
          steps:
            - run:
                name: Install dependencies with NPM
                command: npm install # replace with `yarn install` if using yarn
      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test # replace with `yarn test` if using yarn

      - store_artifacts: 
          path: test-results

      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-with-orb
      - build-without-orb